import React, { createContext, useContext, useState } from "react";

const translations = {
  ru: {
    nav: {
      catalog: "Каталог",
      reviews: "Отзывы",
      faq: "FAQ",
      profile: "Профиль",
      logout: "Выйти",
      login: "Войти",
      register: "Регистрация",
    },
    hero: {
      title: "Авто из\nКитая\nпод ключ",
      order: "ОФОРМИТЬ ЗАКАЗ",
      catalog: "КАТАЛОГ",
    },
    catalog: {
      title: "Рекомендуем",
      cars: "Популярные автомобили",
      parts: "Запчасти",
      toCatalog: "ПЕРЕЙТИ В КАТАЛОГ",
      tabCars: "Автомобили",
      partNames: ["Фильтр масляный", "Тормозные колодки", "Аккумулятор", "Фара левая", "Свечи зажигания"],
      f: {
        country: "Страна", brand: "Марка", model: "Модель",
        gearbox: "Коробка", drive: "Привод", body: "Кузов",
        price: "Цена", year: "Год выпуска", mileage: "Пробег",
        more: "+ Ещё", hide: "Скрыть", from: "От", to: "До",
      },
      ui: {
        loading: "Загрузка...", empty: "Ничего не найдено",
        select: "Подобрать", carsCount: "авто", partsCount: "запчастей",
        loginRequired: "Войдите в систему, чтобы создать заявку.",
        priceFrom: "от",
        reqCarDesc: "Заявка на",
        reqPartDesc: "Заявка на запчасть",
        reqFor: "для",
        chooseFile: "Выберите файл",
        requestSent: "Заявка отправлена",
        requestNum: "№",
      },
      gearboxMap: {
        "Automatic": "Автомат", "Manual": "Механика", "CVT": "Вариатор",
        "DSG": "DSG", "DSG/Robot": "Робот", "Tiptronic": "Типтроник",
      },
      driveMap: {
        "FWD": "Передний", "RWD": "Задний", "AWD": "Полный", "4WD": "Полный",
      },
      bodyMap: {
        "Sedan": "Седан", "SUV": "Внедорожник", "Hatchback": "Хэтчбек",
        "Crossover": "Кроссовер", "Minivan": "Минивэн", "Pickup": "Пикап",
        "Coupe": "Купе", "Wagon": "Универсал", "Convertible": "Кабриолет",
        "Liftback": "Лифтбэк", "Van": "Фургон",
        "Лифтбек": "Лифтбэк",
      },
      countryMap: {
        "China": "Китай", "Korea": "Корея", "Japan": "Япония",
        "Germany": "Германия", "USA": "США", "France": "Франция",
        "Italy": "Италия", "Sweden": "Швеция", "UK": "Великобритания", "Czech Republic": "Чехия",
      },
    },
    reviews: {
      title: "Отзывы клиентов",
      items: [
        { text: "Отличный сервис! Быстро помогли подобрать нужные запчасти для моего Haval F7. Цена оказалась ниже, чем я ожидал, а доставка пришла раньше срока. Всё чётко, без лишних слов — рекомендую всем.", author: "Иван Петров" },
        { text: "Очень доволен покупкой автомобиля через этот каталог. Всё честно и прозрачно — никаких скрытых платежей. Менеджер был на связи на каждом этапе, Chery Tiggo 8 Pro приехал точно в срок и в идеальном состоянии.", author: "Елена Смирнова" },
        { text: "Поддержка всегда на связи и быстро отвечает на любые вопросы. Когда возникли нюансы с таможней, команда DragonAuto взяла всё на себя. Теперь советую компанию всем своим друзьям без исключения.", author: "Алексей Кузнецов" },
        { text: "Удобный интерфейс и широкий выбор автомобилей. Нашла Geely Atlas Pro по отличной цене, оставила заявку — менеджер перезвонил уже через час. Весь процесс от оплаты до получения прошёл без единой заминки.", author: "Мария Иванова" },
        { text: "Хорошие цены и оперативная доставка запчастей. Заказывал оригинальные детали для BYD Han — пришли раньше заявленного срока и в отличной упаковке. Буду обращаться снова, уже без малейших сомнений.", author: "Дмитрий Соколов" },
      ],
    },
    faq: {
      title: "Вопросы и ответы",
      items: [
        {
          q: "Как оформить заказ?",
          a: "Выберите автомобиль в каталоге или опишите желаемую модель в заявке. Мы свяжемся с вами в течение 24 часов.",
        },
        {
          q: "Как долго идёт доставка?",
          a: "Срок доставки из Китая составляет от 30 до 60 дней в зависимости от типа груза и способа доставки.",
        },
        {
          q: "Какие гарантии вы предоставляете?",
          a: "Мы работаем только с проверенными поставщиками и предоставляем полный пакет документов на каждый автомобиль.",
        },
        {
          q: "Можно ли заказать запчасти?",
          a: "Да, мы занимаемся доставкой оригинальных и аналоговых запчастей для любых марок автомобилей.",
        },
      ],
    },
    contact: {
      title: "Как с нами связаться",
      phoneLabel: "Контактный номер:",
      addressLabel: "Адрес:",
      address: "г. Челябинск, Салавата Юлаева д.29",
      phone: "+7 (982) 290-00-86",
      email: "nonashi@mail.ru",
      telegram: "Telegram",
    },
    toasts: {
      profileLoadFail: "Не удалось загрузить профиль",
      profileSaved: "Профиль обновлён",
      profileSaveError: "Ошибка при сохранении",
      codeSendError: "Ошибка при отправке кода",
      emailUpdated: "Email изменён",
      codeInvalid: "Неверный или истёкший код",
      passwordMismatch: "Пароли не совпадают",
      passwordUpdated: "Пароль обновлён",
      requestsLoadFail: "Не удалось загрузить заявки",
      requestCancelled: "Заявка отменена",
      requestCancelFail: "Не удалось отменить заявку",
      requestClosed: "Заявка закрыта",
      requestCloseFail: "Не удалось закрыть заявку",
      offerAccepted: "Предложение принято!",
      offerAcceptFail: "Не удалось принять предложение",
      requestUpdated: "Заявка обновлена",
      fileTooLarge: "Файл не должен превышать 5 МБ",
      fillAllFields: "Заполните все поля",
      acceptPrivacy: "Примите политику конфиденциальности",
      codeSent: "Код подтверждения отправлен на email",
      registerSuccess: "Регистрация успешна!",
      enterCode: "Введите код",
      emailConfirmed: "Email подтверждён!",
      tokenFail: "Не удалось получить токен",
      connectionError: "Ошибка соединения",
      carSubmitted: "Автомобиль отправлен на модерацию",
      partSubmitted: "Запчасть отправлена на модерацию",
      submitError: "Ошибка отправки",
      genericError: "Ошибка",
      productsLoadFail: "Не удалось загрузить товары",
      productUpdated: "Товар обновлён и отправлен на модерацию",
      networkError: "Ошибка сети",
      itemMatched: "Товар привязан, поставщик уведомлён",
      matchRemoved: "Привязка удалена",
      statusUpdated: "Статус обновлён",
      deleteError: "Ошибка удаления",
      loadError: "Ошибка при загрузке данных",
      saveError: "Ошибка при сохранении",
      deleteSuccess: "Запись удалена",
      photoError: "Ошибка загрузки фото",
      loginRequired: "Войдите в систему, чтобы создать заявку",
      requestSent: "Заявка отправлена",
      matchConfirmed: "Подтверждено",
      matchDeclined: "Отклонено",
      supplierStatusPending: "Ожидает подтверждения",
      supplierStatusConfirmed: "Подтверждён",
      supplierStatusDeclined: "Отклонён",
      noActiveRequests: "Нет активных запросов",
      noActiveRequestsHint: "Здесь появятся заявки, в которых модератор выбрал ваш товар",
      appLoadFail: "Не удалось загрузить данные",
      moderationApproved: "Одобрено",
      moderationRejected: "Отклонено",
      moderationFail: "Ошибка модерации",
      validationError: "Заполните все обязательные поля",
      catalogLoadFail: "Не удалось загрузить каталог",
      itemDeleteFail: "Ошибка удаления товара",
      itemSaved: "Товар сохранён",
      itemAdded: "Позиция успешно добавлена",
      changesSaved: "Изменения сохранены",
    },
    footer: {
      company: "DragonAuto",
      legal: "ИП Иванов Георгий",
      address: "г. Челябинск, Салавата Юлаева д.29",
      phone: "+7 982 290 00 86",
    },
    profile: {
      title: "Профиль",
      myRequests: "Мои заявки",
      myProducts: "Мои товары",
      supplierBadge: "Поставщик",
      adminPanel: "Панель админа",
      logout: "Выйти",
      roles: {
        admin: "Администратор",
        moderator: "Модератор",
        supplier: "Поставщик",
        client: "Клиент",
      },
    },
    profileInfo: {
      personal: "Личные данные",
      firstName: "Имя",
      lastName: "Фамилия",
      save: "Сохранить",
      cancel: "Отмена",
      edit: "Редактировать",
      emailChange: "Смена email",
      newEmail: "Новый email",
      sendCode: "Отправить код",
      codeSent: "Код отправлен на текущий email",
      codeLabel: "Код из письма",
      confirm: "Подтвердить",
      back: "Назад",
      passwordChange: "Смена пароля",
      currentPassword: "Текущий пароль",
      newPassword: "Новый пароль",
      repeatPassword: "Повторите новый пароль",
      updatePassword: "Обновить пароль",
    },
    requests: {
      title: "Мои заявки",
      loading: "Загрузка...",
      empty: "Заявок пока нет",
      edit: "Редактировать",
      close: "Закрыть",
      cancel: "Отменить",
      typeCar: "Автомобиль",
      typePart: "Запчасть",
      acceptOffer: "Принять предложение",
      markDone: "Выполнено",
      offerFound: "Найден вариант:",
      offerDescription: "Менеджер нашёл подходящий вариант. Нажмите «Принять предложение» для подтверждения.",
      statuses: {
        "в обработке": "В обработке",
        "в работе":    "В работе",
        "предложение": "Предложение",
        "согласована": "Согласована",
        "выполнена":   "Выполнена",
        "отменена":    "Отменена",
        обработка:     "В обработке",
        отменено:      "Отменена",
      },
    },
    comments: {
      placeholder: "Написать сообщение…",
      send: "Отправить",
      empty: "Сообщений пока нет",
      loading: "Загрузка…",
    },
    chat: {
      statusActive: "Менеджер подключился",
      statusBot: "Виртуальный помощник",
      newConversation: "Новый диалог",
      loading: "Загрузка…",
      placeholder: "Написать сообщение…",
      manager: "Менеджер",
    },
    moderator: {
      application: "Заявка #",
      loading: "Загрузка…",
      noData: "Нет данных",
      reply: "Ответить по e-mail",
      changeStatus: "Изменить статус",
      newStatus: "Новый статус",
      offerPrice: "Цена предложения (₽)",
      offerPricePlaceholder: "Например: 2100000",
      commentOptional: "Комментарий (необязательно)",
      commentPlaceholder: "Пояснение к изменению статуса…",
      save: "Сохранить",
      saving: "Сохраняю…",
      supplierItem: "Товар поставщика",
      matchItem: "+ Подобрать товар поставщика",
      searchPlaceholder: "Поиск по марке, модели, названию…",
      noItems: "Нет одобренных товаров",
      cancelMatch: "Отмена",
      unbind: "Отвязать",
      conversation: "Переписка с поставщиком",
      noMessages: "Сообщений нет",
      replyPlaceholder: "Написать поставщику…",
      supplierStatuses: {
        pending: "Ожидает ответа",
        confirmed: "Подтверждён",
        declined: "Отклонён",
      },
    },
    createRequest: {
      title: "Создать заявку",
      subtitle: "Укажите параметры — мы подберём подходящие варианты",
      tabCar: "Автомобиль",
      tabPart: "Запчасть",
    },
    carForm: {
      country: "Страна",
      brand: "Марка",
      model: "Модель",
      year: "Год выпуска",
      price: "Цена, ₽",
      mileage: "Пробег, км",
      power: "Мощность, л.с.",
      body: "Кузов",
      gearbox: "Коробка",
      drive: "Привод",
      comment: "Комментарий",
      commentPlaceholder: "Дополнительные пожелания…",
      submit: "Отправить заявку",
      submitting: "Отправка…",
      errors: {
        country: "Выберите страну",
        brand: "Введите марку",
        yearFrom: "Укажите год от",
        yearTo: "Укажите год до",
        yearToLess: "Год «до» меньше «от»",
        priceFrom: "Укажите цену от",
        priceTo: "Укажите цену до",
        priceToLess: "Цена «до» меньше «от»",
        mileageFrom: "Укажите пробег от",
        mileageTo: "Укажите пробег до",
        mileageToLess: "Пробег «до» меньше «от»",
        powerFrom: "Укажите мощность от",
        powerTo: "Укажите мощность до",
        powerToLess: "Мощность «до» меньше «от»",
        required: "Заполните обязательные поля",
      },
    },
    partForm: {
      partName: "Название запчасти",
      partNamePlaceholder: "Например, амортизатор задний",
      country: "Страна",
      carBrand: "Марка авто",
      carModel: "Модель авто",
      body: "Кузов",
      price: "Цена, ₽",
      comment: "Комментарий",
      commentPlaceholder: "Год выпуска авто, VIN, дополнительные пожелания…",
      submit: "Отправить заявку",
      submitting: "Отправка…",
      errors: {
        name: "Введите название",
        country: "Выберите страну",
        brand: "Введите марку",
        body: "Выберите кузов",
        priceFrom: "Укажите цену от",
        priceTo: "Укажите цену до",
        priceToLess: "Цена «до» меньше «от»",
        required: "Заполните обязательные поля",
      },
    },
    supplier: {
      myProducts: "Мои товары",
      matchedRequests: "Запросы",
      addCar: "+ Авто",
      addPart: "+ Запчасть",
      loading: "Загрузка…",
      noProducts: "Нет добавленных товаров",
      addFirst: "Добавить первый",
      carLabel: "Автомобиль",
      partLabel: "Запчасть",
      addCarTitle: "Добавить автомобиль",
      addPartTitle: "Добавить запчасть",
      statuses: {
        pending: "На модерации",
        approved: "Одобрено",
        rejected: "Отклонено",
      },
      form: {
        brand: "Марка",
        model: "Модель",
        country: "Страна",
        year: "Год",
        price: "Цена, ₽",
        mileage: "Пробег, км",
        body: "Кузов",
        gearbox: "Коробка",
        drive: "Привод",
        power: "Мощность, л.с.",
        carPhoto: "Фото автомобиля (необязательно)",
        partPhoto: "Фото запчасти (необязательно)",
        submit: "Отправить на модерацию",
        submitting: "Отправка…",
        partName: "Название запчасти",
        carBrand: "Марка авто",
        carModel: "Модель авто",
        carYear: "Год выпуска авто",
        required: "Заполните обязательные поля",
      },
    },
    admin: {
      title: "Панель администратора",
      subtitle: "Управление каталогом, поставщиками и заявками",
      profileLink: "Профиль",
      nav: {
        catalog: "Каталог",
        chatbot: "Чат-бот",
        moderation: "Модерация поставщиков",
        suppliers: "Поставщики",
        applications: "Заявки",
      },
      catalog: {
        title: "Каталог",
        subtitle: "Позиции каталога, добавленные администратором",
        tabCars: "Автомобили",
        tabParts: "Запчасти",
        searchCars: "Поиск по марке, модели…",
        searchParts: "Поиск по названию…",
        allCountries: "Все страны",
        newerFirst: "Сначала новые",
        olderFirst: "Сначала старые",
        found: "Найдено:",
        page: "Страница",
        of: "из",
        noItems: "Нет позиций",
        editBtn: "Изменить",
        editTitle: "Редактировать",
        addBtn: "Добавить",
        addTitle: "Добавить",
        addSaving: "Создание…",
        addSuccess: "Добавлено",
        carWord: "автомобиль",
        partWord: "запчасть",
        save: "Сохранить",
        saving: "Сохранение…",
        cancel: "Отмена",
        deleteTitle: "Удалить позицию?",
        deleteWarning: "Все незакрытые заявки клиентов будут автоматически отменены, а клиенты получат уведомление на почту.",
        confirmDelete: "Да, удалить",
        confirmDeleteFinal: "Подтвердить удаление",
        deleting: "Удаление…",
        irreversible: "Подтвердите ещё раз — это действие необратимо",
        fields: {
          brand: "Бренд",
          model: "Модель",
          year: "Год",
          price: "Цена",
          country: "Страна",
          mileage: "Пробег",
          body: "Кузов",
          gearbox: "КПП",
          drive: "Привод",
          power: "Мощность",
          photoUrl: "Фото URL",
          status: "Статус",
          description: "Описание",
          name: "Название",
          photo: "Фото",
          changePhoto: "Заменить фото…",
          changeTo: "Изменить на",
          choose: "Выберите…",
          mileageUnit: "км",
          powerUnit: "л.с.",
        },
        statuses: {
          approved: "Одобрено",
          pending: "На модерации",
          rejected: "Отклонено",
        },
      },
      chatbot: {
        title: "Чат с клиентами",
        subtitle: "Диалоги, в которых клиент запросил живого менеджера",
        newCount: "новых",
        loading: "Загрузка…",
        empty: "Нет открытых диалогов",
        guest: "Гость",
        statusActive: "Активный",
        statusPending: "Ожидает",
        closeBtn: "Закрыть диалог",
        closing: "—",
        labelClient: "Клиент",
        labelBot: "Бот",
        replyPlaceholder: "Ответить клиенту…",
        selectHint: "Выберите диалог слева",
      },
      moderation: {
        title: "Модерация поставщиков",
        subtitle: "Новые позиции каталога от поставщиков, ожидающие проверки",
        allTypes: "Все типы",
        cars: "Автомобили",
        parts: "Запчасти",
        newerFirst: "Сначала новые",
        olderFirst: "Сначала старые",
        loading: "Загрузка…",
        empty: "Нет заявок на модерацию",
        approve: "Одобрить",
        reject: "Отклонить",
        carBadge: "Авто",
        partBadge: "Запчасть",
        supplierLabel: "Поставщик:",
      },
      suppliers: {
        title: "Поставщики",
        subtitle: "Управление учётными записями поставщиков",
        loading: "Загрузка…",
        empty: "Поставщики не найдены",
        blocked: "Заблокирован",
        block: "Заблокировать",
        unblock: "Разблокировать",
        regDate: "Зарег.:",
      },
      applications: {
        title: "Заявки",
        subtitle: "Заявки клиентов — из каталога и через кнопку «Оформить заказ»",
        all: "Все",
        cars: "Автомобили",
        parts: "Запчасти",
        loading: "Загрузка…",
        empty: "Заявок нет",
        requestPrefix: "Заявка #",
        complete: "Выполнить",
        cancel: "Отменить",
        details: {
          brand: "Бренд",
          model: "Модель",
          country: "Страна",
          priceFrom: "Цена от",
          priceTo: "Цена до",
          yearFrom: "Год от",
          yearTo: "Год до",
          mileageTo: "Пробег до",
          gearbox: "КПП",
          body: "Кузов",
          drive: "Привод",
          power: "Мощность",
          part: "Запчасть",
          comment: "Комментарий",
        },
        statuses: {
          pending: "Ожидает",
          approved: "Одобрено",
          rejected: "Отклонено",
          "в обработке": "В обработке",
          "в работе":    "В работе",
          "предложение": "Предложение",
          "согласована": "Согласована",
          "выполнена":   "Выполнена",
          "отменена":    "Отменена",
          отменено: "Отменено",
        },
      },
    },
  },
  en: {
    nav: {
      catalog: "Catalog",
      reviews: "Reviews",
      faq: "FAQ",
      profile: "Profile",
      logout: "Logout",
      login: "Login",
      register: "Register",
    },
    hero: {
      title: "Cars from\nChina\nturnkey",
      order: "PLACE ORDER",
      catalog: "CATALOG",
    },
    catalog: {
      title: "Recommended",
      cars: "Popular Cars",
      parts: "Spare Parts",
      toCatalog: "GO TO CATALOG",
      tabCars: "Cars",
      partNames: ["Oil Filter", "Brake Pads", "Car Battery", "Left Headlight", "Spark Plugs"],
      f: {
        country: "Country", brand: "Brand", model: "Model",
        gearbox: "Gearbox", drive: "Drive", body: "Body",
        price: "Price", year: "Year", mileage: "Mileage",
        more: "+ More", hide: "Hide", from: "From", to: "To",
      },
      ui: {
        loading: "Loading...", empty: "Nothing found",
        select: "Select", carsCount: "cars", partsCount: "parts",
        loginRequired: "Please log in to create a request.",
        priceFrom: "from",
        reqCarDesc: "Request for",
        reqPartDesc: "Request for spare part",
        reqFor: "for",
        chooseFile: "Choose file",
        requestSent: "Request submitted",
        requestNum: "#",
        langNotice: "Product names and descriptions may appear in Russian",
      },
      gearboxMap: {
        "Автоматическая": "Automatic", "Механическая": "Manual",
        "Вариатор": "CVT", "Робот": "DSG/Robot", "Автомат": "Automatic",
        "АКПП": "Automatic", "Механика": "Manual", "DSG": "DSG",
        "Типтроник": "Tiptronic", "Преселективная": "DSG/Robot",
        "Automatic": "Automatic", "Manual": "Manual", "CVT": "CVT",
        "DSG/Robot": "DSG/Robot", "Tiptronic": "Tiptronic",
      },
      driveMap: {
        "Передний": "FWD", "Задний": "RWD", "Полный": "AWD", "Полный (4WD)": "AWD",
        "FWD": "FWD", "RWD": "RWD", "AWD": "AWD", "4WD": "AWD",
      },
      bodyMap: {
        "Седан": "Sedan", "SUV": "SUV", "Хэтчбек": "Hatchback",
        "Кроссовер": "Crossover", "Минивэн": "Minivan", "Пикап": "Pickup",
        "Купе": "Coupe", "Универсал": "Wagon", "Кабриолет": "Convertible",
        "Лифтбэк": "Liftback", "Лифтбек": "Liftback", "Фургон": "Van",
        "Внедорожник": "SUV",
        "Sedan": "Sedan", "Hatchback": "Hatchback", "Crossover": "Crossover",
        "Minivan": "Minivan", "Pickup": "Pickup", "Coupe": "Coupe",
        "Wagon": "Wagon", "Convertible": "Convertible", "Liftback": "Liftback",
        "Van": "Van",
      },
      countryMap: {
        "Китай": "China", "Корея": "Korea", "Япония": "Japan",
        "Германия": "Germany", "США": "USA", "Франция": "France",
        "Италия": "Italy", "Швеция": "Sweden",
        "Великобритания": "UK", "Чехия": "Czech Republic",
        "China": "China", "Korea": "Korea", "Japan": "Japan",
        "Germany": "Germany", "USA": "USA", "France": "France",
        "Italy": "Italy", "Sweden": "Sweden", "UK": "UK", "Czech Republic": "Czech Republic",
      },
    },
    reviews: {
      title: "Customer Reviews",
      items: [
        { text: "Excellent service! They quickly helped find the right parts for my Haval F7. The price was lower than expected and delivery arrived ahead of schedule. Everything was handled smoothly — highly recommend.", author: "Ivan Petrov" },
        { text: "Very happy with my car purchase through this catalog. Honest and transparent — no hidden fees at all. The manager kept me informed at every step, and my Chery Tiggo 8 Pro arrived on time and in perfect condition.", author: "Elena Smirnova" },
        { text: "Support is always available and responds quickly to any question. When customs issues came up, the DragonAuto team handled everything without any fuss. I now recommend this company to all my friends.", author: "Alexey Kuznetsov" },
        { text: "User-friendly interface and a wide selection of vehicles. Found a Geely Atlas Pro at a great price, submitted a request and a manager called back within an hour. The whole process from payment to delivery was flawless.", author: "Maria Ivanova" },
        { text: "Good prices and fast delivery of spare parts. Ordered genuine parts for my BYD Han — they arrived earlier than promised and were packaged perfectly. Will definitely order again without any hesitation.", author: "Dmitry Sokolov" },
      ],
    },
    faq: {
      title: "Questions & Answers",
      items: [
        {
          q: "How do I place an order?",
          a: "Choose a car from the catalog or describe the desired model in a request. We will contact you within 24 hours.",
        },
        {
          q: "How long does delivery take?",
          a: "Delivery from China takes 30 to 60 days depending on the type of cargo and shipping method.",
        },
        {
          q: "What guarantees do you provide?",
          a: "We only work with verified suppliers and provide a full set of documents for each vehicle.",
        },
        {
          q: "Can I order spare parts?",
          a: "Yes, we deliver original and analog spare parts for any car brand.",
        },
      ],
    },
    contact: {
      title: "How to contact us",
      phoneLabel: "Phone number:",
      addressLabel: "Address:",
      address: "Chelyabinsk, Salavata Yulaeva 29",
      phone: "+7 (982) 290-00-86",
      email: "nonashi@mail.ru",
      telegram: "Telegram",
    },
    toasts: {
      profileLoadFail: "Failed to load profile",
      profileSaved: "Profile updated",
      profileSaveError: "Save error",
      codeSendError: "Failed to send code",
      emailUpdated: "Email updated",
      codeInvalid: "Invalid or expired code",
      passwordMismatch: "Passwords don't match",
      passwordUpdated: "Password updated",
      requestsLoadFail: "Failed to load requests",
      requestCancelled: "Request cancelled",
      requestCancelFail: "Failed to cancel request",
      requestClosed: "Request closed",
      requestCloseFail: "Failed to close request",
      offerAccepted: "Offer accepted!",
      offerAcceptFail: "Failed to accept offer",
      requestUpdated: "Request updated",
      fileTooLarge: "File must not exceed 5 MB",
      fillAllFields: "Fill in all fields",
      acceptPrivacy: "Accept the privacy policy",
      codeSent: "Confirmation code sent to email",
      registerSuccess: "Registration successful!",
      enterCode: "Enter the code",
      emailConfirmed: "Email confirmed!",
      tokenFail: "Failed to get token",
      connectionError: "Connection error",
      carSubmitted: "Car submitted for review",
      partSubmitted: "Spare part submitted for review",
      submitError: "Submit error",
      genericError: "Error",
      productsLoadFail: "Failed to load products",
      productUpdated: "Product updated and submitted for review",
      networkError: "Network error",
      itemMatched: "Product matched, supplier notified",
      matchRemoved: "Match removed",
      statusUpdated: "Status updated",
      deleteError: "Delete error",
      loadError: "Failed to load data",
      saveError: "Save error",
      deleteSuccess: "Record deleted",
      photoError: "Photo upload error",
      loginRequired: "Please log in to create a request",
      requestSent: "Request submitted",
      matchConfirmed: "Confirmed",
      matchDeclined: "Declined",
      supplierStatusPending: "Awaiting confirmation",
      supplierStatusConfirmed: "Confirmed",
      supplierStatusDeclined: "Declined",
      noActiveRequests: "No active requests",
      noActiveRequestsHint: "Requests where a moderator has selected your product will appear here",
      appLoadFail: "Failed to load data",
      moderationApproved: "Approved",
      moderationRejected: "Rejected",
      moderationFail: "Moderation error",
      validationError: "Fill in all required fields",
      catalogLoadFail: "Failed to load catalog",
      itemDeleteFail: "Failed to delete product",
      itemSaved: "Product saved",
      itemAdded: "Entry added successfully",
      changesSaved: "Changes saved",
    },
    footer: {
      company: "DragonAuto",
      legal: "IE Ivanov Georgy",
      address: "Chelyabinsk, Salavata Yulaeva 29",
      phone: "+7 982 290 00 86",
    },
    profile: {
      title: "Profile",
      myRequests: "My Requests",
      myProducts: "My Products",
      supplierBadge: "Supplier",
      adminPanel: "Admin Panel",
      logout: "Logout",
      roles: {
        admin: "Administrator",
        moderator: "Moderator",
        supplier: "Supplier",
        client: "Client",
      },
    },
    profileInfo: {
      personal: "Personal Data",
      firstName: "First Name",
      lastName: "Last Name",
      save: "Save",
      cancel: "Cancel",
      edit: "Edit",
      emailChange: "Change Email",
      newEmail: "New Email",
      sendCode: "Send Code",
      codeSent: "Code sent to your current email",
      codeLabel: "Code from email",
      confirm: "Confirm",
      back: "Back",
      passwordChange: "Change Password",
      currentPassword: "Current Password",
      newPassword: "New Password",
      repeatPassword: "Repeat New Password",
      updatePassword: "Update Password",
    },
    requests: {
      title: "My Requests",
      loading: "Loading...",
      empty: "No requests yet",
      edit: "Edit",
      close: "Close",
      cancel: "Cancel",
      typeCar: "Car",
      typePart: "Spare Part",
      acceptOffer: "Accept offer",
      markDone: "Mark as done",
      offerFound: "Offer found:",
      offerDescription: "Manager found a suitable option. Click \"Accept offer\" to confirm.",
      statuses: {
        "в обработке": "Processing",
        "в работе":    "In Progress",
        "предложение": "Offer",
        "согласована": "Agreed",
        "выполнена":   "Completed",
        "отменена":    "Cancelled",
        обработка:     "In Progress",
        отменено:      "Cancelled",
      },
    },
    comments: {
      placeholder: "Write a message…",
      send: "Send",
      empty: "No messages yet",
      loading: "Loading…",
    },
    chat: {
      statusActive: "Manager connected",
      statusBot: "Virtual assistant",
      newConversation: "New conversation",
      loading: "Loading…",
      placeholder: "Type a message…",
      manager: "Manager",
    },
    moderator: {
      application: "Request #",
      loading: "Loading…",
      noData: "No data",
      reply: "Reply by e-mail",
      changeStatus: "Change Status",
      newStatus: "New Status",
      offerPrice: "Offer price (₽)",
      offerPricePlaceholder: "E.g.: 2100000",
      commentOptional: "Comment (optional)",
      commentPlaceholder: "Note about status change…",
      save: "Save",
      saving: "Saving…",
      supplierItem: "Supplier item",
      matchItem: "+ Match supplier item",
      searchPlaceholder: "Search by brand, model, name…",
      noItems: "No approved items",
      cancelMatch: "Cancel",
      unbind: "Unbind",
      conversation: "Conversation with supplier",
      noMessages: "No messages",
      replyPlaceholder: "Write to supplier…",
      supplierStatuses: {
        pending: "Awaiting response",
        confirmed: "Confirmed",
        declined: "Declined",
      },
    },
    createRequest: {
      title: "Create Request",
      subtitle: "Specify parameters — we'll find the best options",
      tabCar: "Car",
      tabPart: "Spare Part",
    },
    carForm: {
      country: "Country",
      brand: "Brand",
      model: "Model",
      year: "Year",
      price: "Price, ₽",
      mileage: "Mileage, km",
      power: "Power, hp",
      body: "Body Type",
      gearbox: "Gearbox",
      drive: "Drive",
      comment: "Comment",
      commentPlaceholder: "Additional wishes…",
      submit: "Submit Request",
      submitting: "Submitting…",
      errors: {
        country: "Select a country",
        brand: "Enter a brand",
        yearFrom: "Enter year from",
        yearTo: "Enter year to",
        yearToLess: "Year 'to' is less than 'from'",
        priceFrom: "Enter price from",
        priceTo: "Enter price to",
        priceToLess: "Price 'to' is less than 'from'",
        mileageFrom: "Enter mileage from",
        mileageTo: "Enter mileage to",
        mileageToLess: "Mileage 'to' is less than 'from'",
        powerFrom: "Enter power from",
        powerTo: "Enter power to",
        powerToLess: "Power 'to' is less than 'from'",
        required: "Fill in required fields",
      },
    },
    partForm: {
      partName: "Part Name",
      partNamePlaceholder: "E.g., rear shock absorber",
      country: "Country",
      carBrand: "Car Brand",
      carModel: "Car Model",
      body: "Body Type",
      price: "Price, ₽",
      comment: "Comment",
      commentPlaceholder: "Car year, VIN, additional wishes…",
      submit: "Submit Request",
      submitting: "Submitting…",
      errors: {
        name: "Enter a name",
        country: "Select a country",
        brand: "Enter a brand",
        body: "Select body type",
        priceFrom: "Enter price from",
        priceTo: "Enter price to",
        priceToLess: "Price 'to' is less than 'from'",
        required: "Fill in required fields",
      },
    },
    supplier: {
      myProducts: "My Products",
      matchedRequests: "Requests",
      addCar: "+ Car",
      addPart: "+ Part",
      loading: "Loading…",
      noProducts: "No products added",
      addFirst: "Add first",
      carLabel: "Car",
      partLabel: "Spare Part",
      addCarTitle: "Add Car",
      addPartTitle: "Add Spare Part",
      statuses: {
        pending: "Under Review",
        approved: "Approved",
        rejected: "Rejected",
      },
      form: {
        brand: "Brand",
        model: "Model",
        country: "Country",
        year: "Year",
        price: "Price, ₽",
        mileage: "Mileage, km",
        body: "Body Type",
        gearbox: "Gearbox",
        drive: "Drive",
        power: "Power, hp",
        carPhoto: "Car photo (optional)",
        partPhoto: "Part photo (optional)",
        submit: "Submit for Review",
        submitting: "Submitting…",
        partName: "Part Name",
        carBrand: "Car Brand",
        carModel: "Car Model",
        carYear: "Car Year",
        required: "Fill in required fields",
      },
    },
    admin: {
      title: "Admin Panel",
      subtitle: "Manage catalog, suppliers and requests",
      profileLink: "Profile",
      nav: {
        catalog: "Catalog",
        chatbot: "Chatbot",
        moderation: "Supplier Moderation",
        suppliers: "Suppliers",
        applications: "Requests",
      },
      catalog: {
        title: "Catalog",
        subtitle: "Catalog items added by administrator",
        tabCars: "Cars",
        tabParts: "Spare Parts",
        searchCars: "Search by brand, model…",
        searchParts: "Search by name…",
        allCountries: "All Countries",
        newerFirst: "Newer first",
        olderFirst: "Older first",
        found: "Found:",
        page: "Page",
        of: "of",
        noItems: "No items",
        editBtn: "Edit",
        editTitle: "Edit",
        addBtn: "Add",
        addTitle: "Add",
        addSaving: "Creating…",
        addSuccess: "Added",
        carWord: "car",
        partWord: "spare part",
        save: "Save",
        saving: "Saving…",
        cancel: "Cancel",
        deleteTitle: "Delete item?",
        deleteWarning: "All pending client requests will be automatically cancelled and clients will be notified by email.",
        confirmDelete: "Yes, delete",
        confirmDeleteFinal: "Confirm deletion",
        deleting: "Deleting…",
        irreversible: "Confirm again — this action is irreversible",
        fields: {
          brand: "Brand",
          model: "Model",
          year: "Year",
          price: "Price",
          country: "Country",
          mileage: "Mileage",
          body: "Body",
          gearbox: "Gearbox",
          drive: "Drive",
          power: "Power",
          photoUrl: "Photo URL",
          status: "Status",
          description: "Description",
          name: "Name",
          photo: "Photo",
          changePhoto: "Replace photo…",
          changeTo: "Change to",
          choose: "Choose…",
          mileageUnit: "km",
          powerUnit: "hp",
        },
        statuses: {
          approved: "Approved",
          pending: "Under Review",
          rejected: "Rejected",
        },
      },
      chatbot: {
        title: "Client Chat",
        subtitle: "Conversations where the client requested a live manager",
        newCount: "new",
        loading: "Loading…",
        empty: "No open conversations",
        guest: "Guest",
        statusActive: "Active",
        statusPending: "Waiting",
        closeBtn: "Close conversation",
        closing: "—",
        labelClient: "Client",
        labelBot: "Bot",
        replyPlaceholder: "Reply to client…",
        selectHint: "Select a conversation on the left",
      },
      moderation: {
        title: "Supplier Moderation",
        subtitle: "New catalog items from suppliers awaiting review",
        allTypes: "All Types",
        cars: "Cars",
        parts: "Spare Parts",
        newerFirst: "Newer first",
        olderFirst: "Older first",
        loading: "Loading…",
        empty: "No items to moderate",
        approve: "Approve",
        reject: "Reject",
        carBadge: "Car",
        partBadge: "Spare Part",
        supplierLabel: "Supplier:",
      },
      suppliers: {
        title: "Suppliers",
        subtitle: "Manage supplier accounts",
        loading: "Loading…",
        empty: "No suppliers found",
        blocked: "Blocked",
        block: "Block",
        unblock: "Unblock",
        regDate: "Reg.:",
      },
      applications: {
        title: "Requests",
        subtitle: "Client requests — from catalog and via 'Place Order' button",
        all: "All",
        cars: "Cars",
        parts: "Spare Parts",
        loading: "Loading…",
        empty: "No requests",
        requestPrefix: "Request #",
        complete: "Complete",
        cancel: "Cancel",
        details: {
          brand: "Brand",
          model: "Model",
          country: "Country",
          priceFrom: "Price from",
          priceTo: "Price to",
          yearFrom: "Year from",
          yearTo: "Year to",
          mileageTo: "Mileage to",
          gearbox: "Gearbox",
          body: "Body",
          drive: "Drive",
          power: "Power",
          part: "Part",
          comment: "Comment",
        },
        statuses: {
          pending: "Pending",
          approved: "Approved",
          rejected: "Rejected",
          "в обработке": "Processing",
          "в работе":    "In Progress",
          "предложение": "Offer",
          "согласована": "Agreed",
          "выполнена":   "Completed",
          "отменена":    "Cancelled",
          отменено: "Cancelled",
        },
      },
    },
  },
};

const LangContext = createContext();

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("lang") || "ru");

  const toggle = () =>
    setLang((l) => {
      const next = l === "ru" ? "en" : "ru";
      localStorage.setItem("lang", next);
      return next;
    });

  return (
    <LangContext.Provider value={{ lang, toggle, t: translations[lang] }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
